// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	chat "PetPalApp/features/chat"

	mock "github.com/stretchr/testify/mock"
)

// ChatService is an autogenerated mock type for the ChatService type
type ChatService struct {
	mock.Mock
}

// CreateChat provides a mock function with given fields: ChatCore, role
func (_m *ChatService) CreateChat(ChatCore chat.ChatCore, role string) error {
	ret := _m.Called(ChatCore, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(chat.ChatCore, string) error); ok {
		r0 = rf(ChatCore, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: roomChatID, bubbleChatID, senderID, role
func (_m *ChatService) Delete(roomChatID uint, bubbleChatID uint, senderID uint, role string) error {
	ret := _m.Called(roomChatID, bubbleChatID, senderID, role)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, uint, string) error); ok {
		r0 = rf(roomChatID, bubbleChatID, senderID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChats provides a mock function with given fields: currentID, role, roomchatID
func (_m *ChatService) GetChats(currentID uint, role string, roomchatID uint) ([]chat.ChatCore, error) {
	ret := _m.Called(currentID, role, roomchatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChats")
	}

	var r0 []chat.ChatCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string, uint) ([]chat.ChatCore, error)); ok {
		return rf(currentID, role, roomchatID)
	}
	if rf, ok := ret.Get(0).(func(uint, string, uint) []chat.ChatCore); ok {
		r0 = rf(currentID, role, roomchatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.ChatCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string, uint) error); ok {
		r1 = rf(currentID, role, roomchatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChatService creates a new instance of ChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatService {
	mock := &ChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
