// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	consultation "PetPalApp/features/consultation"

	mock "github.com/stretchr/testify/mock"
)

// ConsultationService is an autogenerated mock type for the ConsultationService type
type ConsultationService struct {
	mock.Mock
}

// CreateConsultation provides a mock function with given fields: _a0
func (_m *ConsultationService) CreateConsultation(_a0 consultation.ConsultationCore) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsultation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(consultation.ConsultationCore) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConsultations provides a mock function with given fields: currentID, role
func (_m *ConsultationService) GetConsultations(currentID uint, role string) ([]consultation.ConsultationCore, error) {
	ret := _m.Called(currentID, role)

	if len(ret) == 0 {
		panic("no return value specified for GetConsultations")
	}

	var r0 []consultation.ConsultationCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) ([]consultation.ConsultationCore, error)); ok {
		return rf(currentID, role)
	}
	if rf, ok := ret.Get(0).(func(uint, string) []consultation.ConsultationCore); ok {
		r0 = rf(currentID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consultation.ConsultationCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(currentID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConsultationsByDoctorID provides a mock function with given fields: doctorID
func (_m *ConsultationService) GetConsultationsByDoctorID(doctorID uint) ([]consultation.ConsultationCore, error) {
	ret := _m.Called(doctorID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsultationsByDoctorID")
	}

	var r0 []consultation.ConsultationCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]consultation.ConsultationCore, error)); ok {
		return rf(doctorID)
	}
	if rf, ok := ret.Get(0).(func(uint) []consultation.ConsultationCore); ok {
		r0 = rf(doctorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consultation.ConsultationCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(doctorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConsultationsByUserID provides a mock function with given fields: userID
func (_m *ConsultationService) GetConsultationsByUserID(userID uint) ([]consultation.ConsultationCore, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetConsultationsByUserID")
	}

	var r0 []consultation.ConsultationCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]consultation.ConsultationCore, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []consultation.ConsultationCore); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consultation.ConsultationCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCuntationsById provides a mock function with given fields: id
func (_m *ConsultationService) GetCuntationsById(id uint) (*consultation.ConsultationCore, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCuntationsById")
	}

	var r0 *consultation.ConsultationCore
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*consultation.ConsultationCore, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *consultation.ConsultationCore); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consultation.ConsultationCore)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConsultation provides a mock function with given fields: consulID, Core
func (_m *ConsultationService) UpdateConsultation(consulID uint, Core consultation.ConsultationCore) error {
	ret := _m.Called(consulID, Core)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConsultation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, consultation.ConsultationCore) error); ok {
		r0 = rf(consulID, Core)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsultationService creates a new instance of ConsultationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsultationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsultationService {
	mock := &ConsultationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
