// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HelperuserInterface is an autogenerated mock type for the HelperuserInterface type
type HelperuserInterface struct {
	mock.Mock
}

// ConvertToNullableString provides a mock function with given fields: value
func (m *HelperuserInterface) ConvertToNullableString(input string) *string {
	args := m.Called(input)
	return args.Get(0).(*string)
}

func (m *HelperuserInterface) DereferenceString(input *string) string {
	args := m.Called(input)
	return args.String(0)
}

// NewHelperuserInterface creates a new instance of HelperuserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelperuserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HelperuserInterface {
	mock := &HelperuserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
