// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	order "PetPalApp/features/order"

	mock "github.com/stretchr/testify/mock"

	payment "PetPalApp/features/payment"
)

// PaymentModel is an autogenerated mock type for the PaymentModel type
type PaymentModel struct {
	mock.Mock
}

// FindOrCreatePayment provides a mock function with given fields: orderID, _a1
func (_m *PaymentModel) FindOrCreatePayment(orderID uint, _a1 payment.Payment) (payment.Payment, error) {
	ret := _m.Called(orderID, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreatePayment")
	}

	var r0 payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, payment.Payment) (payment.Payment, error)); ok {
		return rf(orderID, _a1)
	}
	if rf, ok := ret.Get(0).(func(uint, payment.Payment) payment.Payment); ok {
		r0 = rf(orderID, _a1)
	} else {
		r0 = ret.Get(0).(payment.Payment)
	}

	if rf, ok := ret.Get(1).(func(uint, payment.Payment) error); ok {
		r1 = rf(orderID, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: orderID
func (_m *PaymentModel) GetOrderByID(orderID uint) (*order.Order, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*order.Order, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(uint) *order.Order); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByID provides a mock function with given fields: paymentID
func (_m *PaymentModel) GetPaymentByID(paymentID uint) (*payment.Payment, error) {
	ret := _m.Called(paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 *payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*payment.Payment, error)); ok {
		return rf(paymentID)
	}
	if rf, ok := ret.Get(0).(func(uint) *payment.Payment); ok {
		r0 = rf(paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: orderID
func (_m *PaymentModel) GetUserByID(orderID uint) (*payment.User, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *payment.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*payment.User, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(uint) *payment.User); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: orderID, _a1
func (_m *PaymentModel) Update(orderID uint, _a1 payment.Payment) (payment.Payment, error) {
	ret := _m.Called(orderID, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 payment.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, payment.Payment) (payment.Payment, error)); ok {
		return rf(orderID, _a1)
	}
	if rf, ok := ret.Get(0).(func(uint, payment.Payment) payment.Payment); ok {
		r0 = rf(orderID, _a1)
	} else {
		r0 = ret.Get(0).(payment.Payment)
	}

	if rf, ok := ret.Get(1).(func(uint, payment.Payment) error); ok {
		r1 = rf(orderID, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentModel creates a new instance of PaymentModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentModel {
	mock := &PaymentModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
