// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	user "PetPalApp/features/user"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *UserService) Create(input user.Core) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(user.Core) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *UserService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProfile provides a mock function with given fields: id
func (_m *UserService) GetProfile(id uint) (*user.Core, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*user.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *user.Core); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password
func (_m *UserService) Login(email string, password string) (*user.Core, string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.Core
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*user.Core, string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *user.Core); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateById provides a mock function with given fields: id, input, file, handlerFilename
func (_m *UserService) UpdateById(id uint, input user.Core, file io.Reader, handlerFilename string) (string, error) {
	ret := _m.Called(id, input, file, handlerFilename)

	if len(ret) == 0 {
		panic("no return value specified for UpdateById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, user.Core, io.Reader, string) (string, error)); ok {
		return rf(id, input, file, handlerFilename)
	}
	if rf, ok := ret.Get(0).(func(uint, user.Core, io.Reader, string) string); ok {
		r0 = rf(id, input, file, handlerFilename)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint, user.Core, io.Reader, string) error); ok {
		r1 = rf(id, input, file, handlerFilename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
